# Generated by Django 5.0 on 2023-12-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_servicio_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioproducto',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
